name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: AStorozh
          outputs: |
            dist/github-snake.svg?color_snake=%23000000&color_dots=%23EBEDF0,%23FFF4B8,%23FFD700,%23D4AF37,%23B8860B
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23000000&color_dots=%23161B22,%233A3000,%236B5200,%23B8860B,%23FFD700

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
